# See https://hub.docker.com/_/nextcloud
volumes:
  db:
  web:

services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cache:
    image: bitnami/redis:7.4
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  web:
    image: linuxserver/swag:2.11.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - app
    environment:
      - PUID=999
      - PGID=999
      - TZ=Europe/Madrid
      - URL=${NEXTCLOUD_DOMAIN}
      - SUBDOMAINS=
      - VALIDATION=${CERTBOT_VALIDATION:-http}
      - DNSPLUGIN=${CERTBOT_DNSPLUGIN:-}
      - DUCKDNSTOKEN=${CERTBOT_DUCKDNSTOKEN}
    volumes:
      - ${STORAGE_FOLDER:-./data}:/var/www/html:z,ro
      - web:/config
      - ./web/site-confs:/config/nginx/site-confs
    ports:
      - ${HTTPS_PORT:-443}:443
      - ${HTTP_PORT:-80}:80

  app:
    build:
      context: ./app/image
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION}
    restart: unless-stopped
    links:
      - db
      - cache
    volumes:
      - ${STORAGE_FOLDER:-./data}:/var/www/html
      - ./app/hooks.d:/docker-entrypoint-hooks.d
      - ./app/shlib:/_/shlib
      - type: tmpfs
        target: /tmp:exec
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DOMAIN=${NEXTCLOUD_DOMAIN}
      - NEXTCLOUD_DOMAIN_ALT=${NEXTCLOUD_DOMAIN_ALT}
      - NEXTCLOUD_MAINTENANCE_WINDOW_START=${NEXTCLOUD_MAINTENANCE_WINDOW_START}
      - NEXTCLOUD_MAINTENANCE_WINDOW_STOP=${NEXTCLOUD_MAINTENANCE_WINDOW_STOP}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - DEFAULT_PHONE_REGION=${DEFAULT_PHONE_REGION}
      - ENABLE_FILESYSTEM_SCAN=${ENABLE_FILESYSTEM_SCAN:-1}

  cron:
    build:
      context: ./app/image
      args:
        NEXTCLOUD_VERSION: ${NEXTCLOUD_VERSION}
    restart: unless-stopped
    volumes:
      - ${STORAGE_FOLDER:-./data}:/var/www/html
    environment:
      - NEXTCLOUD_MAINTENANCE_WINDOW_START=${NEXTCLOUD_MAINTENANCE_WINDOW_START}
      - NEXTCLOUD_MAINTENANCE_WINDOW_STOP=${NEXTCLOUD_MAINTENANCE_WINDOW_STOP}
    entrypoint: /cron.sh
    depends_on:
      - app
