# See https://hub.docker.com/_/nextcloud
version: '3'

volumes:
  nextcloud:
  nextcloud-db:
  keycloak-db:
    driver: local

services:
  nextcloud-db:
    image: mariadb:10.6.4
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-cache:
    build: 
      context: './redis'
      args:
        redis_password: ${NEXTCLOUD_CACHE_PASSWORD}
    restart: always

  nextcloud:
    build: './nextcloud'
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud-db
      - nextcloud-cache
    volumes:
      - nextcloud:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - REDIS_HOST_PASSWORD=${NEXTCLOUD_CACHE_PASSWORD}

  keycloak-db:
      image: mariadb:latest
      volumes:
        - keycloak-db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
  
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: keycloak-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      ports:
        - 8180:8080
      depends_on:
        - keycloak-db