# See https://hub.docker.com/_/nextcloud
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    build: './mariadb'
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Ch4ngeMe!
      - MYSQL_PASSWORD=Ch4ngeMe!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cache:
    build: './redis'
    restart: always

  app:
    build: './nextcloud'
    restart: always
    ports:
      - 8080:80
    links:
      - db
      - cache
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=Ch4ngeMe!
      - MYSQL_PASSWORD=Ch4ngeMe!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - REDIS_HOST_PASSWORD=Ch4ngeMe!
      # TODO: Store redis.conf password on a secure place
      # TODO: Test using S3 compatible storage --> Minio: https://hub.docker.com/r/minio/minio/
