# See https://hub.docker.com/_/nextcloud
version: '3.8'

volumes:
  db:
  web:

services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cache:
    image: bitnami/redis:7.2
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  web:
    image: linuxserver/swag:2.8.0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - app
    environment:
      - PUID=999
      - PGID=999
      - TZ=Europe/Madrid
      - URL=${NEXTCLOUD_DOMAIN}
      - SUBDOMAINS=
      - VALIDATION=http
    volumes:
      - ${STORAGE_FOLDER:-./data}:/var/www/html:z,ro
      - web:/config
    ports:
      - 443:443
      - 80:80

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}-fpm
    restart: unless-stopped
    links:
      - db
      - cache
    volumes:
      - ${STORAGE_FOLDER:-./data}:/var/www/html
      - ./hooks.d:/docker-entrypoint-hooks.d
      - ./_shlib:/_shlib
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DOMAIN=${NEXTCLOUD_DOMAIN}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}

  cron:
    image: nextcloud:${NEXTCLOUD_VERSION}-fpm
    restart: unless-stopped
    volumes:
      - ${STORAGE_FOLDER:-./data}:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - app
