# See https://hub.docker.com/_/nextcloud
version: '2'

volumes:
  data:
  db:

services:
  db:
    image: mariadb:lts 
    #build: './mariadb'
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cache:
    build: 
      context: './redis'
      args:
        redis_password: ${REDIS_PASSWORD}
    restart: always

  app:
    build: './nextcloud'
    restart: always
    ports:
      - ${NEXTCLOUD_PORT:-8080}:80
    links:
      - db
      - cache
    volumes:
      - data:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DOMAIN=${NEXTCLOUD_DOMAIN}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
