# See https://hub.docker.com/_/nextcloud
version: '2'

volumes:
  data:
  db:

services:
  db:
    image: mariadb:lts
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  cache:
    image: bitnami/redis:7.2
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  app:
    image: nextcloud:28
    #build: './nextcloud'
    restart: always
    ports:
      - ${NEXTCLOUD_PORT:-8080}:80
    links:
      - db
      - cache
    volumes:
      - data:/var/www/html
      - ./hooks.d:/docker-entrypoint-hooks.d
      - ./_shlib:/_shlib
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - NEXTCLOUD_UPDATE=1
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - NEXTCLOUD_DOMAIN=${NEXTCLOUD_DOMAIN}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=cache
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
